# Default Database Configuration (MySQL)
db.type=mysql
db.host=localhost
db.port=3306
db.name=tallerwebi
db.username=user
db.password=user

# PostgreSQL Configuration (uncomment and adjust if needed)
#db.type=postgres
#db.host=localhost
#db.port=5432
#db.name=postgres
#db.username=postgres
#db.password=3420
