
CREATE TABLE Usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    nombre VARCHAR(255),
    apellido VARCHAR(255),
    telefono VARCHAR(255),
    rol VARCHAR(255),
    activo BOOLEAN,
    PRIMARY KEY (id)
);

CREATE TABLE ReporteMascota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_de_reporte VARCHAR(255),
    nombre VARCHAR(255),
    especie VARCHAR(255),
    raza VARCHAR(255),
    color VARCHAR(255),
    tamano VARCHAR(255),
    fecha DATE,
    ubicacion VARCHAR(255),
    descripcion VARCHAR(255),
    fecha_creacion_reporte TIMESTAMP,
    registro_activo BOOLEAN,
    usuario_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (usuario_id) REFERENCES Usuario(id)
);

CREATE TABLE Foto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    img VARCHAR(255),
    reporte_mascota_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (reporte_mascota_id) REFERENCES ReporteMascota(id)
);
